name: fastai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fastai
  - defaults
dependencies:
  - fastai::fastai>=2.7.15
  - fastai::fastbook>=0.0.28
  - fastai::fastcore>=1.5.33
  - fastai::fastkaggle>=0.0.8
  - fastai::fastprogress>=1.0.3
  - pytorch::pytorch-mutex=*=cuda
  - pytorch::pytorch>=2.3.0
  - pytorch::torchvision>=0.18.0
  - pytorch::torchaudio>=2.3.0
  - anaconda
  - anaconda-navigator
  - datasets
  - diffusers
  - dtreeviz
  - einops
  - kaggle
  - gradio
  - graphviz
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nbdev
  - pandas
  - pip
  - plotly
  - python=3.12
  - scikit-learn
  - seaborn
  - sentencepiece
  - statsmodels
  - timm
  - transformers
  - treeinterpreter
  - waterfallcharts
  - pip:
    - azure-cognitiveservices-search-imagesearch
    - duckduckgo_search
    - torcheval
